In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(
    "C:/Users/jawah/OneDrive/Desktop/MCA MINI PROJECT - Copy/AI-Tech-Job-Market-Skills-Analytics/Data/raw/Dataset2.xlsx"
)

In [3]:
df.head()

,job_id,company_name,title,description,max_salary,pay_period,formatted_work_type,location,company_id,views,...,skills_desc,listed_time,posting_domain,sponsored,work_type,currency,compensation_type,normalized_salary,zip_code,fips
0,921716,CORCORAN SAWYER SMITH,Marketing Coordinator,Job Descriptiona Leading Real Estate Firm In N...,20.0,HOURLY,FULL-TIME,"Princeton, NJ",2774458,20.0,...,Requirements: \n\nWe are seeking a College or ...,1713397508000,NaN,0,FULL_TIME,USD,BASE_SALARY,38480.0,8540.0,34021.0
1,10998357,THE NATIONAL EXEMPLAR,Assitant Restaurant Manager,The National Exemplar Is Accepting Application...,65000.0,YEARLY,FULL-TIME,"Cincinnati, OH",64896719,8.0,...,We are currently accepting resumes for FOH - A...,1713277614000,NaN,0,FULL_TIME,USD,BASE_SALARY,55000.0,45202.0,39061.0
2,23221523,"ABRAMS FENSTERMAN, LLP",Senior Elder Law / Trusts And Estates Associat...,Senior Associate Attorney - Elder Law / Trusts...,175000.0,YEARLY,FULL-TIME,"New Hyde Park, NY",766262,16.0,...,This position requires a baseline understandin...,1712895812000,NaN,0,FULL_TIME,USD,BASE_SALARY,157500.0,11040.0,36059.0
3,91700727,DOWNTOWN RALEIGH ALLIANCE,Economic Development And Planning Intern,Job Summary:The Economic Development & Plannin...,20.0,HOURLY,INTERNSHIP,"Raleigh, NC",1481176,9.0,...,NaN,1713456099000,NaN,0,INTERNSHIP,USD,BASE_SALARY,35360.0,27601.0,37183.0
4,103254301,RAW CEREAL,Producer,Company Descriptionraw Cereal Is A Creative De...,300000.0,YEARLY,CONTRACT,United States,81942316,7.0,...,NaN,1712861019000,NaN,0,CONTRACT,USD,BASE_SALARY,180000.0,NaN,NaN

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122129 entries, 0 to 122128
Data columns (total 31 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      122129 non-null  int64
 1   company_name                122129 non-null  object
 2   title                       122129 non-null  object
 3   description                 122123 non-null  object
 4   max_salary                  29338 non-null   float64
 5   pay_period                  35563 non-null   object
 6   formatted_work_type         122129 non-null  object
 7   location                    122129 non-null  object
 8   company_id                  122129 non-null  int64
 9   views                       120502 non-null  float64
 10  med_salary                  6225 non-null    float64
 11  min_salary                  29338 non-null   float64
 12  applies                     22895 non-null   float64
 13  original_listed_time        122129 non-null  int64
 14  remote_allowed              14814 non-null   float64
 15  job_posting_url             122129 non-null  object
 16  application_url             87069 non-null   object
 17  application_type            122129 non-null  object
 18  expiry                      122129 non-null  int64
 19  closed_time                 1056 non-null    float64
 20  formatted_experience_level  94182 non-null   object
 21  skills_desc                 2436 non-null    object
 22  listed_time                 122129 non-null  int64
 23  posting_domain              83880 non-null   object
 24  sponsored                   122129 non-null  int64
 25  work_type                   122129 non-null  object
 26  currency                    35563 non-null   object
 27  compensation_type           35563 non-null   object
 28  normalized_salary           35563 non-null   float64
 29  zip_code                    101855 non-null  float64
 30  fips                        95391 non-null   float64
dtypes: float64(10), int64(6), object(15)
memory usage: 28.9+ MB

In [6]:
df.columns

Index(['job_id', 'company_name', 'title', 'description', 'max_salary',
       'pay_period', 'formatted_work_type', 'location', 'company_id', 'views',
       'med_salary', 'min_salary', 'applies', 'original_listed_time',
       'remote_allowed', 'job_posting_url', 'application_url',
       'application_type', 'expiry', 'closed_time',
       'formatted_experience_level', 'skills_desc', 'listed_time',
       'posting_domain', 'sponsored', 'work_type', 'currency',
       'compensation_type', 'normalized_salary', 'zip_code', 'fips'],
      dtype='object')

In [9]:
df.shape

(122129, 31)

In [11]:
df.isna().sum()

job_id                             0
company_name                       0
title                              0
description                        6
max_salary                     92791
pay_period                     86566
formatted_work_type                0
location                           0
company_id                         0
views                           1627
med_salary                    115904
min_salary                     92791
applies                        99234
original_listed_time               0
remote_allowed                107315
job_posting_url                    0
application_url                35060
application_type                   0
expiry                             0
closed_time                   121073
formatted_experience_level     27947
skills_desc                   119693
listed_time                        0
posting_domain                 38249
sponsored                          0
work_type                          0
currency                       86566
compensation_type              86566
normalized_salary              86566
zip_code                       20274
fips                           26738
dtype: int64

In [14]:
missing_summary = pd.DataFrame({
    "Missing_Count": df.isnull().sum(),
    "Missing_Percentage": df.isnull().mean().mul(100).round(2)
})

missing_summary

                            Missing_Count  Missing_Percentage
job_id                                  0                0.00
company_name                            0                0.00
title                                   0                0.00
description                             6                0.00
max_salary                          92791               75.98
pay_period                          86566               70.88
formatted_work_type                     0                0.00
location                                0                0.00
company_id                              0                0.00
views                                1627                1.33
med_salary                         115904               94.90
min_salary                          92791               75.98
applies                             99234               81.25
original_listed_time                    0                0.00
remote_allowed                     107315               87.87
job_posting_url                         0                0.00
application_url                     35060               28.71
application_type                        0                0.00
expiry                                  0                0.00
closed_time                        121073               99.14
formatted_experience_level          27947               22.88
skills_desc                        119693               98.01
listed_time                             0                0.00
posting_domain                      38249               31.32
sponsored                               0                0.00
work_type                               0                0.00
currency                            86566               70.88
compensation_type                   86566               70.88
normalized_salary                   86566               70.88
zip_code                            20274               16.60
fips                                26738               21.89

In [15]:
missing_summary.sort_values(
    "Missing_Percentage",
    ascending=False
)

                            Missing_Count  Missing_Percentage
closed_time                        121073               99.14
skills_desc                        119693               98.01
med_salary                         115904               94.90
remote_allowed                     107315               87.87
applies                             99234               81.25
min_salary                          92791               75.98
max_salary                          92791               75.98
currency                            86566               70.88
compensation_type                   86566               70.88
pay_period                          86566               70.88
normalized_salary                   86566               70.88
posting_domain                      38249               31.32
application_url                     35060               28.71
formatted_experience_level          27947               22.88
fips                                26738               21.89
zip_code                            20274               16.60
views                                1627                1.33
company_id                              0                0.00
job_id                                  0                0.00
title                                   0                0.00
company_name                            0                0.00
description                             6                0.00
formatted_work_type                     0                0.00
original_listed_time                    0                0.00
location                                0                0.00
application_type                        0                0.00
expiry                                  0                0.00
listed_time                             0                0.00
job_posting_url                         0                0.00
work_type                               0                0.00
sponsored                               0                0.00

In [16]:
df["skills_desc"].dropna().head(10)

0       Requirements: \n\nWe are seeking a College or ...
1       We are currently accepting resumes for FOH - A...
2       This position requires a baseline understandin...
5       â€¢ Requires the ability to communicate effect...
6       Knowledge, Skills and Abilities: 1. Proficient...
7       The Production Supervisor must possess strong ...
13      Strong interpersonal communication skills and ...
735     SkillsProject ManagementEducationPHD or better...
994         CDLCPGFIFOManufacturingproductionsupply chain
1498     \n Must Have: Minimum Requirements\n To be co...
Name: skills_desc, dtype: object

In [17]:
df["skills_desc"].dropna().shape

(2436,)

In [18]:
df["formatted_experience_level"].value_counts(dropna=False)

formatted_experience_level
Mid-Senior level    41367
Entry level         36681
NaN                 27947
Associate            9743
Director             3729
Internship           1449
Executive            1213
Name: count, dtype: int64

In [19]:
df["formatted_work_type"].value_counts(dropna=False)

formatted_work_type
FULL-TIME     97551
CONTRACT      11955
PART-TIME      9488
TEMPORARY      1176
INTERNSHIP      955
VOLUNTEER       555
OTHER           449
Name: count, dtype: int64

In [20]:
df["description"].head(5)

0    Job Descriptiona Leading Real Estate Firm In N...
1    The National Exemplar Is Accepting Application...
2    Senior Associate Attorney - Elder Law / Trusts...
3    Job Summary:The Economic Development & Plannin...
4    Company Descriptionraw Cereal Is A Creative De...
Name: description, dtype: object

In [21]:
df["description"].str.len().describe()

count    122123.000000
mean       3803.177067
std        2145.511696
min           2.000000
25%        2214.000000
50%        3472.000000
75%        5024.500000
max       23225.000000
Name: description, dtype: float64

In [22]:
df["description"].isna().sum()

np.int64(6)

In [24]:
df["job_id"].duplicated().sum()

np.int64(0)

In [25]:
df["job_id"].nunique()

122129

In [26]:
df.shape

(122129, 31)

In [27]:
df["job_id"].duplicated().sum()

np.int64(0)

In [28]:
df["job_id"].nunique()

122129

In [29]:
df.shape

(122129, 31)

In [33]:
df["job_id"].duplicated().sum()

np.int64(0)

In [34]:
df["job_id"].nunique()

122129

In [32]:
df.shape

(122129, 31)

In [35]:
df.duplicated().sum()

np.int64(0)

In [36]:
df = df.dropna(subset=["description"]).reset_index(drop=True)

In [37]:
df.shape

(122123, 31)

In [38]:
df["description"].isna().sum()

np.int64(0)

In [39]:
df["formatted_experience_level"] = df["formatted_experience_level"].fillna("Unknown")

In [40]:
df["formatted_experience_level"].value_counts()

formatted_experience_level
Mid-Senior level    41367
Entry level         36681
Unknown             27941
Associate            9743
Director             3729
Internship           1449
Executive            1213
Name: count, dtype: int64

In [41]:
df["remote_allowed"].value_counts(dropna=False)

remote_allowed
NaN    107312
1.0     14811
Name: count, dtype: int64

In [42]:
df["Remote_Status"] = df["remote_allowed"].map({
    1.0: "Yes"
}).fillna("Unknown")

In [43]:
df["Remote_Status"].value_counts()

Remote_Status
Unknown    107312
Yes         14811
Name: count, dtype: int64

In [44]:
df[["min_salary", "max_salary", "med_salary", "pay_period", "currency"]].head(10)

   min_salary  max_salary  med_salary pay_period currency
0        17.0        20.0         NaN     HOURLY      USD
1     45000.0     65000.0         NaN     YEARLY      USD
2    140000.0    175000.0         NaN     YEARLY      USD
3        14.0        20.0         NaN     HOURLY      USD
4     60000.0    300000.0         NaN     YEARLY      USD
5         NaN         NaN         NaN        NaN      NaN
6         NaN         NaN       350.0    MONTHLY      USD
7         NaN         NaN         NaN        NaN      NaN
8         NaN         NaN         NaN        NaN      NaN
9         NaN         NaN         NaN        NaN      NaN

In [45]:
df[["min_salary", "max_salary", "med_salary"]].describe()

         min_salary    max_salary     med_salary
count  2.933700e+04  2.933700e+04    6225.000000
mean   6.510887e+04  9.224478e+04   22007.328514
std    4.997638e+05  7.064583e+05   52387.405476
min    1.000000e+00  1.000000e+00       0.000000
25%    3.800000e+01  4.900000e+01      19.000000
50%    6.020000e+04  8.000000e+04      25.000000
75%    1.000000e+05  1.400000e+05    2500.000000
max    8.500000e+07  1.200000e+08  750000.000000

In [46]:
df["pay_period"].value_counts(dropna=False)

pay_period
NaN         86561
YEARLY      20324
HOURLY      14549
MONTHLY       503
WEEKLY        177
BIWEEKLY        9
Name: count, dtype: int64

In [47]:
df["currency"].value_counts(dropna=False)

currency
NaN    86561
USD    35549
EUR        6
CAD        3
BBD        2
GBP        2
Name: count, dtype: int64

In [48]:
annual_multiplier = {
    "YEARLY": 1,
    "MONTHLY": 12,
    "BIWEEKLY": 26,
    "WEEKLY": 52,
    "HOURLY": 2080
}

df["Salary_Min_Annual"] = (
    df["min_salary"] *
    df["pay_period"].map(annual_multiplier)
)

df["Salary_Max_Annual"] = (
    df["max_salary"] *
    df["pay_period"].map(annual_multiplier)
)

In [49]:
df.loc[df["currency"] != "USD", ["Salary_Min_Annual", "Salary_Max_Annual"]] = pd.NA

In [50]:
df[[
    "min_salary",
    "max_salary",
    "pay_period",
    "currency",
    "Salary_Min_Annual",
    "Salary_Max_Annual"
]].dropna().head(10)

,min_salary,max_salary,pay_period,currency,Salary_Min_Annual,Salary_Max_Annual
0,17.0,20.0,HOURLY,USD,35360.0,41600.0
1,45000.0,65000.0,YEARLY,USD,45000.0,65000.0
2,140000.0,175000.0,YEARLY,USD,140000.0,175000.0
3,14.0,20.0,HOURLY,USD,29120.0,41600.0
4,60000.0,300000.0,YEARLY,USD,60000.0,300000.0
23,55000.0,75000.0,YEARLY,USD,55000.0,75000.0
24,60000.0,65000.0,YEARLY,USD,60000.0,65000.0
25,4061.0,4817.0,MONTHLY,USD,48732.0,57804.0
29,90000.0,110000.0,YEARLY,USD,90000.0,110000.0
30,105000.0,135000.0,YEARLY,USD,105000.0,135000.0

In [51]:
df[["Salary_Min_Annual", "Salary_Max_Annual"]].describe()

       Salary_Min_Annual  Salary_Max_Annual
count       2.932400e+04       2.932400e+04
mean        2.082412e+05       2.664939e+05
std         5.170457e+06       6.144870e+06
min         1.000000e+00       1.000000e+00
25%         5.000000e+04       6.656000e+04
50%         7.530000e+04       1.019200e+05
75%         1.100000e+05       1.500000e+05
max         4.992000e+08       5.720000e+08

In [52]:
df[df["Salary_Max_Annual"] > 1000000][
    ["title", "min_salary", "max_salary", "pay_period",
     "currency", "Salary_Min_Annual", "Salary_Max_Annual"]
].head(20)

,title,min_salary,max_salary,pay_period,currency,Salary_Min_Annual,Salary_Max_Annual
4582,Partner (& Groups W/ Portable Business For Top...,350000.0,1500000.0,YEARLY,USD,350000.0,1500000.0
4628,Partner (& Groups W/ Portable Business For Top...,350000.0,1500000.0,YEARLY,USD,350000.0,1500000.0
4755,Partner (& Groups W/ Portable Business For Top...,350000.0,1500000.0,YEARLY,USD,350000.0,1500000.0
8966,Intellectual Property Associate (246215),240000.0,275000.0,HOURLY,USD,499200000.0,572000000.0
13289,Cloud Domain Architect,125000.0,150000.0,HOURLY,USD,260000000.0,312000000.0
17252,Dcs Technician,70000.0,80000.0,HOURLY,USD,145600000.0,166400000.0
19462,Full Time Field Service Technician Â€“ Wilming...,45000.0,50000.0,HOURLY,USD,93600000.0,104000000.0
19584,"Full Time Field Service Technician Â€“ Tulsa, Ok",42000.0,45000.0,HOURLY,USD,87360000.0,93600000.0
29896,Modernization Software Dev,60000.0,100000.0,MONTHLY,USD,720000.0,1200000.0
34252,Technical Lab Specialist,77000.0,1115000.0,YEARLY,USD,77000.0,1115000.0
39373,Data Engineer,65.0,6570.0,HOURLY,USD,135200.0,13665600.0
40045,Sales Representative- Entry Level ($50K Base +...,50000.0,70000.0,HOURLY,USD,104000000.0,145600000.0
44140,Dotnet Developer,100000.0,1220000.0,YEARLY,USD,100000.0,1220000.0
46902,React Ui Developer,90000.0,110000.0,MONTHLY,USD,1080000.0,1320000.0
47409,Wifi Test Engineer,50.0,5060.0,HOURLY,USD,104000.0,10524800.0
52856,Sales Associate,50000.0,65000.0,HOURLY,USD,104000000.0,135200000.0
58999,Billing Supervisor (246521),125000.0,125000.0,HOURLY,USD,260000000.0,260000000.0
70597,Sharepoint Developer,100000.0,120000.0,HOURLY,USD,208000000.0,249600000.0
71324,Trial Paralegal - Hybrid In Oc Or La!,80000.0,100000.0,HOURLY,USD,166400000.0,208000000.0
78292,Ark Encounter Housekeeping Specialist Full Tim...,29120.0,32240.0,HOURLY,USD,60569600.0,67059200.0

In [53]:
(df["Salary_Max_Annual"] > 1000000).sum()

np.int64(48)

In [54]:
df[df["Salary_Max_Annual"] > 1000000]["Salary_Max_Annual"].describe()

count    4.800000e+01
mean     9.089892e+07
std      1.230917e+08
min      1.000001e+06
25%      1.681032e+06
50%      4.886960e+07
75%      1.238000e+08
max      5.720000e+08
Name: Salary_Max_Annual, dtype: float64

In [55]:
df["Salary_Min_Annual_Clean"] = df["Salary_Min_Annual"]
df["Salary_Max_Annual_Clean"] = df["Salary_Max_Annual"]

df.loc[
    df["Salary_Max_Annual_Clean"] > 1_000_000,
    ["Salary_Min_Annual_Clean", "Salary_Max_Annual_Clean"]
] = pd.NA

In [56]:
df[[
    "Salary_Min_Annual",
    "Salary_Max_Annual",
    "Salary_Min_Annual_Clean",
    "Salary_Max_Annual_Clean"
]].describe()

,Salary_Min_Annual,Salary_Max_Annual,Salary_Min_Annual_Clean,Salary_Max_Annual_Clean
count,2.932400e+04,2.932400e+04,29276.000000,29276.000000
mean,2.082412e+05,2.664939e+05,86153.904495,117895.862037
std,5.170457e+06,6.144870e+06,49563.756449,75380.891749
min,1.000000e+00,1.000000e+00,1.000000,1.000000
25%,5.000000e+04,6.656000e+04,50000.000000,66560.000000
50%,7.530000e+04,1.019200e+05,75000.000000,101525.500000
75%,1.100000e+05,1.500000e+05,110000.000000,150000.000000
max,4.992000e+08,5.720000e+08,750000.000000,1000000.000000

In [57]:
df["Salary_Max_Annual_Clean"].isna().sum()

np.int64(92847)

In [58]:
df["Work_Type_Clean"] = (
    df["formatted_work_type"]
    .str.strip()
    .str.title()
)

In [59]:
df["Work_Type_Clean"].value_counts()

Work_Type_Clean
Full-Time     97545
Contract      11955
Part-Time      9488
Temporary      1176
Internship      955
Volunteer       555
Other           449
Name: count, dtype: int64

In [60]:
df[["formatted_work_type", "Work_Type_Clean"]].drop_duplicates()

    formatted_work_type Work_Type_Clean
0             FULL-TIME       Full-Time
3            INTERNSHIP      Internship
4              CONTRACT        Contract
6             PART-TIME       Part-Time
52            TEMPORARY       Temporary
57            VOLUNTEER       Volunteer
333               OTHER           Other

In [61]:
df["application_type"].value_counts(dropna=False)

application_type
Offsite Apply           84492
Complex Onsite Apply    29930
Simple Onsite Apply      7700
UnknownApply                1
Name: count, dtype: int64

In [62]:
df["Application_Type_Clean"] = df["application_type"].replace({
    "UnknownApply": "Unknown"
})

In [63]:
df["Application_Type_Clean"].value_counts()

Application_Type_Clean
Offsite Apply           84492
Complex Onsite Apply    29930
Simple Onsite Apply      7700
Unknown                     1
Name: count, dtype: int64

In [64]:
df["application_url"].isna().sum()

np.int64(35054)

In [65]:
df["location"].value_counts().head(20)

location
United States                      7844
New York, NY                       2725
Chicago, IL                        1815
Houston, TX                        1740
Dallas, TX                         1370
Atlanta, GA                        1346
Boston, MA                         1166
Austin, TX                         1074
Charlotte, NC                      1073
Phoenix, AZ                        1040
Washington, DC                      978
Los Angeles, CA                     954
San Francisco, CA                   872
Seattle, WA                         810
New York City Metropolitan Area     799
Denver, CO                          783
San Diego, CA                       782
Philadelphia, PA                    697
Tampa, FL                           653
San Antonio, TX                     636
Name: count, dtype: int64

In [66]:
df["location"].nunique()

8462

In [67]:
df["Location_Clean"] = (
    df["location"]
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
)

In [68]:
df[["location", "Location_Clean"]].head(20)

                location        Location_Clean
0          Princeton, NJ         Princeton, NJ
1         Cincinnati, OH        Cincinnati, OH
2      New Hyde Park, NY     New Hyde Park, NY
3            Raleigh, NC           Raleigh, NC
4          United States         United States
5              Omaha, NE             Omaha, NE
6           Palm Bay, FL          Palm Bay, FL
7            Saginaw, MI           Saginaw, MI
8           St Louis, MO          St Louis, MO
9          United States         United States
10         Anchorage, AK         Anchorage, AK
11         Cleveland, OH         Cleveland, OH
12  Greater Philadelphia  Greater Philadelphia
13        Birmingham, AL        Birmingham, AL
14           Atlanta, GA           Atlanta, GA
15           Orlando, FL           Orlando, FL
16            Denver, CO            Denver, CO
17         Harlingen, TX         Harlingen, TX
18            Woburn, MA            Woburn, MA
19  West Bridgewater, MA  West Bridgewater, MA

In [69]:
df["Location_Clean"].value_counts().head(20)

Location_Clean
United States                      7844
New York, NY                       2725
Chicago, IL                        1815
Houston, TX                        1740
Dallas, TX                         1370
Atlanta, GA                        1346
Boston, MA                         1166
Austin, TX                         1074
Charlotte, NC                      1073
Phoenix, AZ                        1040
Washington, DC                      978
Los Angeles, CA                     954
San Francisco, CA                   872
Seattle, WA                         810
New York City Metropolitan Area     799
Denver, CO                          783
San Diego, CA                       782
Philadelphia, PA                    697
Tampa, FL                           653
San Antonio, TX                     636
Name: count, dtype: int64

In [70]:
id="t9zv8m"
df["listed_time"].head(10)

0    1713397508000
1    1713277614000
2    1712895812000
3    1713456099000
4    1712861019000
5    1712348500000
6    1712455955000
7    1713210566000
8    1712858322000
9    1713537397000
Name: listed_time, dtype: int64

In [71]:
id="6z6b7x"
df["listed_time"].dtype

dtype('int64')

In [72]:
id="7v9m2a"
df["listed_time"].isna().sum()

np.int64(0)

In [73]:
df["Listed_DateTime"] = pd.to_datetime(
    df["listed_time"],
    unit="ms"
)

In [74]:
df[["listed_time", "Listed_DateTime"]].head(10)

     listed_time     Listed_DateTime
0  1713397508000 2024-04-17 23:45:08
1  1713277614000 2024-04-16 14:26:54
2  1712895812000 2024-04-12 04:23:32
3  1713456099000 2024-04-18 16:01:39
4  1712861019000 2024-04-11 18:43:39
5  1712348500000 2024-04-05 20:21:40
6  1712455955000 2024-04-07 02:12:35
7  1713210566000 2024-04-15 19:49:26
8  1712858322000 2024-04-11 17:58:42
9  1713537397000 2024-04-19 14:36:37

In [75]:
df["Listed_Date"] = df["Listed_DateTime"].dt.date

In [76]:
df["Listed_Year"] = df["Listed_DateTime"].dt.year
df["Listed_Month"] = df["Listed_DateTime"].dt.month
df["Listed_Month_Name"] = df["Listed_DateTime"].dt.month_name()

In [77]:
df[[
    "Listed_DateTime",
    "Listed_Date",
    "Listed_Year",
    "Listed_Month",
    "Listed_Month_Name"
]].head()

      Listed_DateTime Listed_Date  Listed_Year  Listed_Month Listed_Month_Name
0 2024-04-17 23:45:08  2024-04-17         2024             4             April
1 2024-04-16 14:26:54  2024-04-16         2024             4             April
2 2024-04-12 04:23:32  2024-04-12         2024             4             April
3 2024-04-18 16:01:39  2024-04-18         2024             4             April
4 2024-04-11 18:43:39  2024-04-11         2024             4             April

In [79]:
df = df.drop(columns=["sponsored"])

In [80]:
df.shape

(122123, 43)

In [81]:
final_columns = [
    "job_id",
    "company_name",
    "title",
    "description",
    "location",
    "Location_Clean",
    "formatted_work_type",
    "Work_Type_Clean",
    "formatted_experience_level",
    "application_type",
    "Application_Type_Clean",
    "min_salary",
    "max_salary",
    "pay_period",
    "currency",
    "Salary_Min_Annual_Clean",
    "Salary_Max_Annual_Clean",
    "views",
    "applies",
    "Listed_DateTime",
    "Listed_Date",
    "Listed_Year",
    "Listed_Month",
    "Listed_Month_Name",
    "remote_allowed",
    "Remote_Status",
    "skills_desc",
    "job_posting_url"
]

In [82]:
[c for c in final_columns if c not in df.columns]

[]

In [83]:
df_final = df[final_columns].copy()

In [84]:
df_final.shape

(122123, 28)

In [85]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122123 entries, 0 to 122122
Data columns (total 28 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   job_id                      122123 non-null  int64
 1   company_name                122123 non-null  object
 2   title                       122123 non-null  object
 3   description                 122123 non-null  object
 4   location                    122123 non-null  object
 5   Location_Clean              122123 non-null  object
 6   formatted_work_type         122123 non-null  object
 7   Work_Type_Clean             122123 non-null  object
 8   formatted_experience_level  122123 non-null  object
 9   application_type            122123 non-null  object
 10  Application_Type_Clean      122123 non-null  object
 11  min_salary                  29337 non-null   float64
 12  max_salary                  29337 non-null   float64
 13  pay_period                  35562 non-null   object
 14  currency                    35562 non-null   object
 15  Salary_Min_Annual_Clean     29276 non-null   float64
 16  Salary_Max_Annual_Clean     29276 non-null   float64
 17  views                       120496 non-null  float64
 18  applies                     22893 non-null   float64
 19  Listed_DateTime             122123 non-null  datetime64[ns]
 20  Listed_Date                 122123 non-null  object
 21  Listed_Year                 122123 non-null  int32
 22  Listed_Month                122123 non-null  int32
 23  Listed_Month_Name           122123 non-null  object
 24  remote_allowed              14811 non-null   float64
 25  Remote_Status               122123 non-null  object
 26  skills_desc                 2436 non-null    object
 27  job_posting_url             122123 non-null  object
dtypes: datetime64[ns](1), float64(7), int32(2), int64(1), object(17)
memory usage: 25.2+ MB

In [86]:
df_final.isna().sum().sort_values(ascending=False)

skills_desc                   119687
remote_allowed                107312
applies                        99230
Salary_Min_Annual_Clean        92847
Salary_Max_Annual_Clean        92847
min_salary                     92786
max_salary                     92786
currency                       86561
pay_period                     86561
views                           1627
title                              0
job_id                             0
Application_Type_Clean             0
application_type                   0
formatted_experience_level         0
Work_Type_Clean                    0
Location_Clean                     0
formatted_work_type                0
location                           0
description                        0
company_name                       0
Listed_DateTime                    0
Listed_Date                        0
Listed_Year                        0
Listed_Month_Name                  0
Listed_Month                       0
Remote_Status                      0
job_posting_url                    0
dtype: int64

In [87]:
df_final = df_final.drop(columns=["skills_desc"])

In [88]:
df_final.shape

(122123, 27)

In [89]:
df_final["job_id"].duplicated().sum()

np.int64(0)

In [90]:
print("Shape:", df_final.shape)

Shape: (122123, 27)

In [91]:
print("Duplicate Job IDs:", df_final["job_id"].duplicated().sum())

Duplicate Job IDs: 0

In [92]:
print("Duplicate Rows:", df_final.duplicated().sum())

Duplicate Rows: 0

In [93]:
print("Missing Values:")
print(df_final.isna().sum().sort_values(ascending=False).head(10))

Missing Values:
remote_allowed             107312
applies                     99230
Salary_Max_Annual_Clean     92847
Salary_Min_Annual_Clean     92847
max_salary                  92786
min_salary                  92786
currency                    86561
pay_period                  86561
views                        1627
company_name                    0
dtype: int64

In [94]:
print("Shape:", df_final.shape)
print("Duplicate Job IDs:", df_final["job_id"].duplicated().sum())
print("Duplicate Rows:", df_final.duplicated().sum())

Shape: (122123, 27)
Duplicate Job IDs: 0
Duplicate Rows: 0

In [96]:
output_path = "C:/Users/jawah/OneDrive/Desktop/MCA MINI PROJECT - Copy/AI-Tech-Job-Market-Skills-Analytics/Data/cleaned/Dataset2_Cleaned.csv"

df_final.to_csv(output_path, index=False)

print("Dataset 2 saved successfully!")
print("Shape:", df_final.shape)

Dataset 2 saved successfully!
Shape: (122123, 27)

In [97]:
import os

print(os.path.exists(output_path))

True