In [14]:
import pandas as pd

In [37]:
df = pd.read_excel(
    "C:/Users/jawah/OneDrive/Desktop/MCA MINI PROJECT - Copy/AI-Tech-Job-Market-Skills-Analytics/Data/raw/Dataset1.xlsx"
)

In [38]:
df.head()

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8
0,JOB_TITLES,Company_Names,Experience_Required,Package_Details,Locations,Skills,Post_Url,Post_Time
1,SENIOR MANAGER - DATA SCIENCE,AMERICAN EXPRESS,4-8 Yrs,Not disclosed,"Gurgaon,Gurugram",Text miningCareer developmentdata scienceFinan...,https://www.naukri.com/job-listings-senior-man...,1 Day Ago
2,ADVANCE ANALYTICAL AND DATA SCIENCES -MANAGER,G R Infraprojects,6-10 Yrs,Not disclosed,"Gurgaon, Gurugram, Haryana",Advanced Statistical AnalysisData Governance a...,https://www.naukri.com/job-listings-advance-an...,7 Days Ago
3,MANAGER - DIGITAL PRODUCT ANALYTICS [DATA SCIE...,Resy,4-8 Yrs,Not disclosed,"Gurgaon,Gurugram",Product managementCareer developmentOperations...,https://www.naukri.com/job-listings-manager-di...,4 Days Ago
4,DATA SCIENCE MANAGER,Foreign IT Consulting MNC,1-3 Yrs,Not disclosed,"Mumbai, Hyderabad,Secunderabad, Pune, Gurgaon,...",Change managementSASCodingData miningPythonRst...,NaN,10 Days Ago

In [39]:
df.shape

(43454, 8)

In [40]:
df.columns

Index(['Column1', 'Column2', 'Column3', 'Column4', 'Column5', 'Column6',
       'Column7', 'Column8'],
      dtype='object')

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43454 entries, 0 to 43453
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Column1  43454 non-null  object
 1   Column2  35812 non-null  object
 2   Column3  32416 non-null  object
 3   Column4  34895 non-null  object
 4   Column5  35427 non-null  object
 5   Column6  34292 non-null  object
 6   Column7  36107 non-null  object
 7   Column8  36144 non-null  object
dtypes: object(8)
memory usage: 2.7+ MB

In [42]:
df.isna().sum()

Column1        0
Column2     7642
Column3    11038
Column4     8559
Column5     8027
Column6     9162
Column7     7347
Column8     7310
dtype: int64

In [43]:
# Display the first row
df.iloc[0]

Column1             JOB_TITLES
Column2          Company_Names
Column3    Experience_Required
Column4        Package_Details
Column5              Locations
Column6                 Skills
Column7               Post_Url
Column8              Post_Time
Name: 0, dtype: object

In [44]:
# Use the first row as column names
df.columns = df.iloc[0]

# Remove the first row from the dataset
df = df.iloc[1:].reset_index(drop=True)

# Check the result
df.head()

,JOB_TITLES,Company_Names,Experience_Required,Package_Details,Locations,Skills,Post_Url,Post_Time
0,SENIOR MANAGER - DATA SCIENCE,AMERICAN EXPRESS,4-8 Yrs,Not disclosed,"Gurgaon,Gurugram",Text miningCareer developmentdata scienceFinan...,https://www.naukri.com/job-listings-senior-man...,1 Day Ago
1,ADVANCE ANALYTICAL AND DATA SCIENCES -MANAGER,G R Infraprojects,6-10 Yrs,Not disclosed,"Gurgaon, Gurugram, Haryana",Advanced Statistical AnalysisData Governance a...,https://www.naukri.com/job-listings-advance-an...,7 Days Ago
2,MANAGER - DIGITAL PRODUCT ANALYTICS [DATA SCIE...,Resy,4-8 Yrs,Not disclosed,"Gurgaon,Gurugram",Product managementCareer developmentOperations...,https://www.naukri.com/job-listings-manager-di...,4 Days Ago
3,DATA SCIENCE MANAGER,Foreign IT Consulting MNC,1-3 Yrs,Not disclosed,"Mumbai, Hyderabad,Secunderabad, Pune, Gurgaon,...",Change managementSASCodingData miningPythonRst...,NaN,10 Days Ago
4,DATA SCIENCE MANAGER,Fortune India 500 Company in FMCG,4-9 Yrs,Not disclosed,"Bangalore,Bengaluru",Data analysisdata scienceAnalyticalPredictive ...,NaN,1 Day Ago

In [47]:
df.shape

df.columns.tolist()

['JOB_TITLES',
 'Company_Names',
 'Experience_Required',
 'Package_Details',
 'Locations',
 'Skills',
 'Post_Url',
 'Post_Time']

In [48]:
df.duplicated().sum()

np.int64(22318)

In [52]:
df[df.duplicated()].head()

,JOB_TITLES,Company_Names,Experience_Required,Package_Details,Locations,Skills,Post_Url,Post_Time
11652,DATA SCIENCE CONSULTANT,Blue Yonder,1-3 Yrs,Not disclosed,"Mumbai, Hyderabad,Secunderabad, Pune, Gurgaon,...",Computer scienceContent strategyData analysisU...,https://www.naukri.com/job-listings-manager-di...,4 Days Ago
11662,SENIOR DATA SCIENCE ANALYST,Alliance Data,5-10 Yrs,Not disclosed,"Gurgaon,Gurugram",Data Sciencedata analyticsSASData miningPython...,https://www.naukri.com/job-listings-senior-div...,1 Day Ago
11663,DATA SCIENCE - SENIOR DATA SCIENTIST,Paytm,2-4 Yrs,Not disclosed,"Bangalore,Bengaluru",deep learningdata scienceGCPNeural networksMac...,https://www.naukri.com/job-listings-head-data-...,8 Days Ago
11664,SENIOR MANAGER-DATA SCIENCE,Resy,2-5 Yrs,6-10 Lacs PA,"Mumbai, Hyderabad,Secunderabad, Pune, Gurgaon,...",Data SciencepythonPyTorchArtificial Intelligen...,https://www.naukri.com/job-listings-senior-ana...,1 Day Ago
11665,DATA SCIENCE SPECIALIST,Brunel,4-8 Yrs,Not disclosed,"Bangalore,Bengaluru",Statistical programmingData analysisAutomation...,https://www.naukri.com/job-listings-data-scien...,Just Now

In [54]:
df.drop_duplicates().reset_index(drop = True)

,JOB_TITLES,Company_Names,Experience_Required,Package_Details,Locations,Skills,Post_Url,Post_Time
0,SENIOR MANAGER - DATA SCIENCE,AMERICAN EXPRESS,4-8 Yrs,Not disclosed,"Gurgaon,Gurugram",Text miningCareer developmentdata scienceFinan...,https://www.naukri.com/job-listings-senior-man...,1 Day Ago
1,ADVANCE ANALYTICAL AND DATA SCIENCES -MANAGER,G R Infraprojects,6-10 Yrs,Not disclosed,"Gurgaon, Gurugram, Haryana",Advanced Statistical AnalysisData Governance a...,https://www.naukri.com/job-listings-advance-an...,7 Days Ago
2,MANAGER - DIGITAL PRODUCT ANALYTICS [DATA SCIE...,Resy,4-8 Yrs,Not disclosed,"Gurgaon,Gurugram",Product managementCareer developmentOperations...,https://www.naukri.com/job-listings-manager-di...,4 Days Ago
3,DATA SCIENCE MANAGER,Foreign IT Consulting MNC,1-3 Yrs,Not disclosed,"Mumbai, Hyderabad,Secunderabad, Pune, Gurgaon,...",Change managementSASCodingData miningPythonRst...,NaN,10 Days Ago
4,DATA SCIENCE MANAGER,Fortune India 500 Company in FMCG,4-9 Yrs,Not disclosed,"Bangalore,Bengaluru",Data analysisdata scienceAnalyticalPredictive ...,NaN,1 Day Ago
...,...,...,...,...,...,...,...,...
21130,NONE,NaN,NaN,NaN,NaN,NaN,https://www.naukri.com/job-listings-data-scien...,NaN
21131,NONE,NaN,NaN,NaN,NaN,NaN,https://www.naukri.com/job-listings-senior-man...,NaN
21132,NONE,NaN,NaN,NaN,NaN,NaN,https://www.naukri.com/job-listings-data-scien...,NaN
21133,NONE,NaN,NaN,NaN,NaN,NaN,https://www.naukri.com/job-listings-gn-strateg...,NaN
21134,NONE,NaN,NaN,NaN,NaN,NaN,https://www.naukri.com/job-listings-advance-an...,NaN

In [55]:
print("Shape after removing duplicates:", df.shape)
print("Duplicates remaining:", df.duplicated().sum())

Shape after removing duplicates: (43453, 8)
Duplicates remaining: 22318

In [59]:
df.duplicated().sum()

np.int64(22318)

In [62]:
df.isna().sum()

0
JOB_TITLES                 0
Company_Names           7642
Experience_Required    11038
Package_Details         8559
Locations               8027
Skills                  9162
Post_Url                7347
Post_Time               7310
dtype: int64

In [63]:
(df.isnull().sum() / len(df) * 100).round(2)

0
JOB_TITLES              0.00
Company_Names          17.59
Experience_Required    25.40
Package_Details        19.70
Locations              18.47
Skills                 21.08
Post_Url               16.91
Post_Time              16.82
dtype: float64

In [66]:
missing_text_cols = [
    "JOB_TITLES",
    "Company_Names",
    "Experience_Required",
    "Package_Details",
    "Locations",
    "Skills",
    "Post_Url",
    "Post_Time"
]

for col in missing_text_cols:
    df[col] = df[col].fillna("Unknown")

In [67]:
df.isna().sum()

0
JOB_TITLES             0
Company_Names          0
Experience_Required    0
Package_Details        0
Locations              0
Skills                 0
Post_Url               0
Post_Time              0
dtype: int64

In [ ]:
#Remove unnecessary spaces

for col in missing_text_cols:
    df[col] = df[col].astype(str).str.strip()

In [70]:
df["Experience_Required"].value_counts().head(20)

Experience_Required
Unknown      11038
5-8 Yrs       2815
4-8 Yrs       2762
5-10 Yrs      2716
1-3 Yrs       1973
2-5 Yrs       1810
3-8 Yrs       1666
3-6 Yrs       1619
1-4 Yrs       1591
2-4 Yrs       1574
4-9 Yrs       1545
8-10 Yrs      1384
6-10 Yrs      1363
8-12 Yrs      1361
7-10 Yrs      1343
7-11 Yrs      1300
15-24 Yrs     1281
3-5 Yrs        382
2-7 Yrs        310
2-6 Yrs        261
Name: count, dtype: int64

In [71]:
df["Experience_Required"].unique()[:30]

array(['4-8 Yrs', '6-10 Yrs', '1-3 Yrs', '4-9 Yrs', '8-12 Yrs',
       '15-24 Yrs', '8-10 Yrs', '7-10 Yrs', '5-8 Yrs', '7-11 Yrs',
       '5-10 Yrs', '2-4 Yrs', '2-5 Yrs', '0-0 Yrs', '6-11 Yrs',
       '12-20 Yrs', '3-7 Yrs', '12-15 Yrs', '5-9 Yrs', '8-13 Yrs',
       '5-6 Yrs', '3-5 Yrs', '4-7 Yrs', '3-8 Yrs', '6-8 Yrs', '1-4 Yrs',
       '10-12 Yrs', '8-11 Yrs', '1-5 Yrs', '10-15 Yrs'], dtype=object)

In [74]:
#Create Minimum & Maximum Experience

df["Experience_Min"] = (
    df["Experience_Required"]
    .str.extract(r"(\d+)-\d+")[0]
    .astype("Int64")
)


df["Experience_Max"] = (
    df["Experience_Required"]
    .str.extract(r"\d+-(\d+)")[0]
    .astype("Int64")
)

df[["Experience_Required", "Experience_Min", "Experience_Max"]].head(10)

0 Experience_Required  Experience_Min  Experience_Max
0             4-8 Yrs               4               8
1            6-10 Yrs               6              10
2             4-8 Yrs               4               8
3             1-3 Yrs               1               3
4             4-9 Yrs               4               9
5            8-12 Yrs               8              12
6           15-24 Yrs              15              24
7            8-10 Yrs               8              10
8            7-10 Yrs               7              10
9             5-8 Yrs               5               8

In [77]:
df["Experience_Min"].describe()
df["Experience_Max"].describe()

count     32415.0
mean     8.380133
std      4.225547
min           0.0
25%           5.0
50%           8.0
75%          10.0
max          30.0
Name: Experience_Max, dtype: Float64

In [79]:
#Check salary values

df["Package_Details"].unique()[:30]

array(['Not disclosed', '6-10 Lacs PA', '18-22.5 Lacs PA',
       '2.5-4 Lacs PA', 'Unpaid', '35-45 Lacs PA', '13-18 Lacs PA',
       '7-12 Lacs PA', '35-50 Lacs PA', '4-9 Lacs PA', '10-12 Lacs PA',
       '2.5-7.5 Lacs PA', '10-17 Lacs PA', '18-30 Lacs PA',
       '6-11 Lacs PA', '4-6 Lacs PA', '35-55 Lacs PA', '5.5-10 Lacs PA',
       '2.5-3.75 Lacs PA', '10-20 Lacs PA', '3-5 Lacs PA',
       '20-35 Lacs PA', '12-22 Lacs PA', '14-20 Lacs PA', '5-8 Lacs PA',
       '50,000 PA', '50,000-2 Lacs PA', '6.5-12 Lacs PA', '12-15 Lacs PA',
       '25-40 Lacs PA'], dtype=object)

In [80]:
df.columns.tolist()

['JOB_TITLES',
 'Company_Names',
 'Experience_Required',
 'Package_Details',
 'Locations',
 'Skills',
 'Post_Url',
 'Post_Time',
 'Experience_Min',
 'Experience_Max']

In [83]:
df["Salary_Min_LPA"] = (
    df["Package_Details"]
    .str.extract(r"(\d+)\s*-\s*\d+")[0]
    .astype("Int64")
)

df["Salary_Max_LPA"] = (
    df["Package_Details"]
    .str.extract(r"\d+\s*-\s*(\d+)")[0]
    .astype("Int64")
)

In [84]:
df[[
    "Package_Details",
    "Salary_Min_LPA",
    "Salary_Max_LPA"
]].head(20)

0   Package_Details  Salary_Min_LPA  Salary_Max_LPA
0     Not disclosed            <NA>            <NA>
1     Not disclosed            <NA>            <NA>
2     Not disclosed            <NA>            <NA>
3     Not disclosed            <NA>            <NA>
4     Not disclosed            <NA>            <NA>
5     Not disclosed            <NA>            <NA>
6     Not disclosed            <NA>            <NA>
7     Not disclosed            <NA>            <NA>
8     Not disclosed            <NA>            <NA>
9     Not disclosed            <NA>            <NA>
10    Not disclosed            <NA>            <NA>
11     6-10 Lacs PA               6              10
12    Not disclosed            <NA>            <NA>
13    Not disclosed            <NA>            <NA>
14  18-22.5 Lacs PA              18              22
15    Not disclosed            <NA>            <NA>
16    2.5-4 Lacs PA               5               4
17           Unpaid            <NA>            <NA>
18    Not disclosed            <NA>            <NA>
19    Not disclosed            <NA>            <NA>

In [86]:
#Clean Locations

df["Locations"].value_counts().head(5)

Locations
Bangalore,Bengaluru       8176
Unknown                   8027
Gurgaon,Gurugram          4770
Hyderabad,Secunderabad    3512
Remote                    2669
Name: count, dtype: int64

In [88]:
df["Locations"].unique()[:10]

array(['Gurgaon,Gurugram', 'Gurgaon, Gurugram, Haryana',
       'Mumbai, Hyderabad,Secunderabad, Pune, Gurgaon,Gurugram, Chennai, Bangalore,Bengaluru',
       'Bangalore,Bengaluru', 'Delhi , NCR, Mumbai  (All Areas)',
       'Hyderabad,Secunderabad', 'Pune, Bangalore,Bengaluru',
       'Kolkata, Mumbai, New Delhi, Hyderabad,Secunderabad, Pune, Chennai, Bangalore,Bengaluru',
       'Noida (Sector-126 Noida)', 'Faridabad'], dtype=object)

In [94]:


ocation_replacements = {
    "Bengaluru": "Bangalore",
    "Gurugram": "Gurgaon",
    "Secunderabad": "Hyderabad"
}

for old, new in location_replacements.items():
    df["Locations"] = df["Locations"].str.replace(
        old, new, regex=False
    )

In [90]:
df["Locations"].unique()[:20]

array(['Gurgaon,Gurgaon', 'Gurgaon, Gurgaon, Haryana',
       'Mumbai, Hyderabad,Hyderabad, Pune, Gurgaon,Gurgaon, Chennai, Bangalore,Bangalore',
       'Bangalore,Bangalore', 'Delhi , NCR, Mumbai  (All Areas)',
       'Hyderabad,Hyderabad', 'Pune, Bangalore,Bangalore',
       'Kolkata, Mumbai, New Delhi, Hyderabad,Hyderabad, Pune, Chennai, Bangalore,Bangalore',
       'Noida (Sector-126 Noida)', 'Faridabad', 'Remote',
       'Lucknow, Uttar Pradesh', 'Mumbai, New Delhi', 'Noida',
       'Hybrid - Bangalore,Bangalore',
       'Hyderabad,Hyderabad, Bangalore,Bangalore',
       'Noida, Uttar Pradesh, New Delhi, Delhi, Gurgaon, Gurgaon, Haryana',
       'Hybrid - Noida, Uttar Pradesh', 'Chennai', 'Pune'], dtype=object)

In [95]:
df["Locations_Cleaned"] = df["Locations"].str.replace(
    r"\b(Bangalore|Gurgaon|Hyderabad),\1\b",
    r"\1",
    regex=True
)

In [96]:
df["Locations_Cleaned"] = df["Locations"].copy()

In [97]:
df[["Locations", "Locations_Cleaned"]].head(10)

,Locations,Locations_Cleaned
0,"Gurgaon,Gurgaon","Gurgaon,Gurgaon"
1,"Gurgaon, Gurgaon, Haryana","Gurgaon, Gurgaon, Haryana"
2,"Gurgaon,Gurgaon","Gurgaon,Gurgaon"
3,"Mumbai, Hyderabad,Hyderabad, Pune, Gurgaon,Gur...","Mumbai, Hyderabad,Hyderabad, Pune, Gurgaon,Gur..."
4,"Bangalore,Bangalore","Bangalore,Bangalore"
5,"Bangalore,Bangalore","Bangalore,Bangalore"
6,"Delhi , NCR, Mumbai (All Areas)","Delhi , NCR, Mumbai (All Areas)"
7,"Hyderabad,Hyderabad","Hyderabad,Hyderabad"
8,"Pune, Bangalore,Bangalore","Pune, Bangalore,Bangalore"
9,"Hyderabad,Hyderabad","Hyderabad,Hyderabad"

In [98]:
#removing duplicate values

def remove_duplicate_locations(value):
    locations = [x.strip() for x in value.split(",")]
    
    unique_locations = []
    for location in locations:
        if location not in unique_locations:
            unique_locations.append(location)
    
    return ", ".join(unique_locations)

df["Locations_Cleaned"] = df["Locations_Cleaned"].apply(
    remove_duplicate_locations
)

In [99]:
df[["Locations", "Locations_Cleaned"]].head(15)

,Locations,Locations_Cleaned
0,"Gurgaon,Gurgaon",Gurgaon
1,"Gurgaon, Gurgaon, Haryana","Gurgaon, Haryana"
2,"Gurgaon,Gurgaon",Gurgaon
3,"Mumbai, Hyderabad,Hyderabad, Pune, Gurgaon,Gur...","Mumbai, Hyderabad, Pune, Gurgaon, Chennai, Ban..."
4,"Bangalore,Bangalore",Bangalore
5,"Bangalore,Bangalore",Bangalore
6,"Delhi , NCR, Mumbai (All Areas)","Delhi, NCR, Mumbai (All Areas)"
7,"Hyderabad,Hyderabad",Hyderabad
8,"Pune, Bangalore,Bangalore","Pune, Bangalore"
9,"Hyderabad,Hyderabad",Hyderabad
10,"Kolkata, Mumbai, New Delhi, Hyderabad,Hyderaba...","Kolkata, Mumbai, New Delhi, Hyderabad, Pune, C..."
11,Noida (Sector-126 Noida),Noida (Sector-126 Noida)
12,"Bangalore,Bangalore",Bangalore
13,Faridabad,Faridabad
14,Remote,Remote

In [100]:
df["Skills"].head(10)

0    Text miningCareer developmentdata scienceFinan...
1    Advanced Statistical AnalysisData Governance a...
2    Product managementCareer developmentOperations...
3    Change managementSASCodingData miningPythonRst...
4    Data analysisdata scienceAnalyticalPredictive ...
5    deep learningdata scienceGCPNeural networksMac...
6    Data SciencepythonPyTorchArtificial Intelligen...
7    Statistical programmingData analysisAutomation...
8    NoSQLManager Quality AssuranceGCPMachine learn...
9    Data analysisdata scienceAnalyticalMachine lea...
Name: Skills, dtype: object

In [101]:
df["Skills"].value_counts().head(10)

Skills
Unknown                                                                                                                   9162
Text miningCareer developmentdata scienceFinanceMachine learningData miningStakeholder managementSQL                      2596
Data analysisdata scienceAnalyticalMachine learningHTMLMonitoringFinancial servicesSQL                                    1299
Statistical programmingData analysisAutomationAnalyticalMachine learningAgileOpen sourceSQL                               1299
NoSQLManager Quality AssuranceGCPMachine learningSCALAData processingData qualityAnalytics                                1299
Data analysisdata scienceAnalyticalPredictive modelingRisk managementData miningForecastingFinancial services             1298
deep learningdata scienceGCPNeural networksMachine learningCloudData processingSubject Matter Expert                      1298
Data ModelingPythonSQlDataData analysisScienceModelingData Science                                                        1298
Data analysisEDCRisk assessmentrisk modelingMachine learningData processingmodel developmentFinancial services            1298
Product managementCareer developmentOperations researchData modelingAnalyticalRelationship buildingMachine learningSQL    1298
Name: count, dtype: int64

In [103]:
df["Skills"].str.len().describe()

count    43453.000000
mean        78.198674
std         44.185555
min          6.000000
25%         49.000000
50%         90.000000
75%        110.000000
max        287.000000
Name: Skills, dtype: float64

In [102]:
df["Skills"].unique()[:10]

array(['Text miningCareer developmentdata scienceFinanceMachine learningData miningStakeholder managementSQL',
       'Advanced Statistical AnalysisData Governance and Quality AssuranceMachine Learning and AIData Analysis and VisualizationManagementQuality assuranceArtificial IntelligenceData Visualization',
       'Product managementCareer developmentOperations researchData modelingAnalyticalRelationship buildingMachine learningSQL',
       'Change managementSASCodingData miningPythonRstatistic techniquesDebugging',
       'Data analysisdata scienceAnalyticalPredictive modelingRisk managementData miningForecastingFinancial services',
       'deep learningdata scienceGCPNeural networksMachine learningCloudData processingSubject Matter Expert',
       'Data SciencepythonPyTorchArtificial IntelligenceLarge language ManagementMachine LearningTensorFlowIntelligence',
       'Statistical programmingData analysisAutomationAnalyticalMachine learningAgileOpen sourceSQL',
       'NoSQLManager Quality AssuranceGCPMachine learningSCALAData processingData qualityAnalytics',
       'Data analysisdata scienceAnalyticalMachine learningHTMLMonitoringFinancial servicesSQL'],
      dtype=object)

In [108]:
skill_list = [
    "Python",
    "SQL",
    "NoSQL",
    "R",
    "Java",
    "C++",
    "C#",
    "JavaScript",
    "Machine Learning",
    "Deep Learning",
    "Data Science",
    "Data Analysis",
    "Data Mining",
    "Artificial Intelligence",
    "Natural Language Processing",
    "NLP",
    "Computer Vision",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "GCP",
    "AWS",
    "Azure",
    "Power BI",
    "Tableau",
    "Hadoop",
    "Spark",
    "Statistics",
    "Predictive Modeling"
]

In [109]:
for skill in skill_list:
    count = df["Skills"].str.contains(
        skill,
        case=False,
        na=False,
        regex=False
    ).sum()
    
    if count > 0:
        print(f"{skill}: {count}")

Python: 7425
SQL: 12626
NoSQL: 2705
R: 32662
Java: 294
C++: 206
C#: 3
JavaScript: 207
Machine Learning: 20935
Deep Learning: 1594
Data Science: 17536
Data Analysis: 11233
Data Mining: 7901
Artificial Intelligence: 5559
Natural Language Processing: 566
NLP: 1366
Computer Vision: 139
TensorFlow: 1373
PyTorch: 1356
Keras: 20
Scikit-learn: 21
GCP: 2845
AWS: 203
Azure: 247
Power BI: 1930
Tableau: 662
Hadoop: 102
Spark: 212
Statistics: 170
Predictive Modeling: 1442

In [110]:
import re

def count_skill(skill):
    pattern = r"\b" + re.escape(skill) + r"\b"
    return df["Skills"].str.contains(
        pattern,
        case=False,
        na=False,
        regex=True
    ).sum()

In [111]:
for skill in skill_list:
    count = count_skill(skill)
    if count > 0:
        print(f"{skill}: {count}")

Python: 4
SQL: 76
NoSQL: 2
R: 4
C++: 50
C#: 2
Machine Learning: 7
Deep Learning: 3
Data Science: 3
Data Analysis: 3
Natural Language Processing: 1
Computer Vision: 1
GCP: 4
AWS: 7
Azure: 79
Power BI: 17
Tableau: 10
Hadoop: 3
Predictive Modeling: 1

In [114]:
#Create 0/1 columns
skill_list_clean = [
    "Python",
    "SQL",
    "NoSQL",
    "Java",
    "C++",
    "C#",
    "JavaScript",
    "Machine Learning",
    "Deep Learning",
    "Data Science",
    "Data Analysis",
    "Data Mining",
    "Artificial Intelligence",
    "Natural Language Processing",
    "NLP",
    "Computer Vision",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Scikit-learn",
    "GCP",
    "AWS",
    "Azure",
    "Power BI",
    "Tableau",
    "Hadoop",
    "Spark",
    "Statistics",
    "Predictive Modeling"
]

In [115]:
import re

for skill in skill_list_clean:
    column_name = skill.replace(" ", "_").replace("-", "_")

    pattern = r"\b" + re.escape(skill) + r"\b"

    df[column_name] = (
        df["Skills"]
        .str.contains(
            pattern,
            case=False,
            na=False,
            regex=True
        )
        .astype("Int64")
    )

In [ ]:
#check the results

df[[
    "Skills",
    "Python",
    "SQL",
    "NoSQL",
    "Machine_Learning",
    "Data_Science",
    "Data_Analysis",
    "Power_BI"
]].head(10)

,Skills,Python,SQL,NoSQL,Machine_Learning,Data_Science,Data_Analysis,Power_BI
0,Text miningCareer developmentdata scienceFinan...,0,0,0,0,0,0,0
1,Advanced Statistical AnalysisData Governance a...,0,0,0,0,0,0,0
2,Product managementCareer developmentOperations...,0,0,0,0,0,0,0
3,Change managementSASCodingData miningPythonRst...,0,0,0,0,0,0,0
4,Data analysisdata scienceAnalyticalPredictive ...,0,0,0,0,0,0,0
5,deep learningdata scienceGCPNeural networksMac...,0,0,0,0,0,0,0
6,Data SciencepythonPyTorchArtificial Intelligen...,0,0,0,0,0,0,0
7,Statistical programmingData analysisAutomation...,0,0,0,0,0,0,0
8,NoSQLManager Quality AssuranceGCPMachine learn...,0,0,0,0,0,0,0
9,Data analysisdata scienceAnalyticalMachine lea...,0,0,0,0,0,0,0

In [117]:
#check the totals

skill_totals = {}

for skill in skill_list_clean:
    column_name = skill.replace(" ", "_").replace("-", "_")
    skill_totals[skill] = df[column_name].sum()

skill_totals

{'Python': np.int64(4),
 'SQL': np.int64(76),
 'NoSQL': np.int64(2),
 'Java': np.int64(0),
 'C++': np.int64(50),
 'C#': np.int64(2),
 'JavaScript': np.int64(0),
 'Machine Learning': np.int64(7),
 'Deep Learning': np.int64(3),
 'Data Science': np.int64(3),
 'Data Analysis': np.int64(3),
 'Data Mining': np.int64(0),
 'Artificial Intelligence': np.int64(0),
 'Natural Language Processing': np.int64(1),
 'NLP': np.int64(0),
 'Computer Vision': np.int64(1),
 'TensorFlow': np.int64(0),
 'PyTorch': np.int64(0),
 'Keras': np.int64(0),
 'Scikit-learn': np.int64(0),
 'GCP': np.int64(4),
 'AWS': np.int64(7),
 'Azure': np.int64(79),
 'Power BI': np.int64(17),
 'Tableau': np.int64(10),
 'Hadoop': np.int64(3),
 'Spark': np.int64(0),
 'Statistics': np.int64(0),
 'Predictive Modeling': np.int64(1)}

In [ ]:
#elete the skill columns we just created.
for skill in skill_list_clean:
    column_name = skill.replace(" ", "_").replace("-", "_")
    df.drop(columns=column_name, inplace=True, errors="ignore")

In [119]:
df.shape

(43453, 14)

In [120]:
#clean posttime

df["Post_Time"].value_counts().head(30)

Post_Time
Unknown                 7310
1 Day Ago               6502
30+ Days Ago            6195
4 Days Ago              5033
8 Days Ago              1696
10 Days Ago             1619
28 Days Ago             1607
17 Days Ago             1587
7 Days Ago              1582
2 Days Ago              1581
5 Days Ago              1482
11 Days Ago             1441
Starts in 1-3 months    1364
23 Days Ago             1237
Few Hours Ago            946
Just Now                 407
15 Days Ago              199
14 Days Ago              187
9 Days Ago               166
22 Days Ago              145
18 Days Ago              141
30 Days Ago              140
29 Days Ago              135
16 Days Ago              134
24 Days Ago              133
21 Days Ago              124
Today                     69
27 Days Ago               66
6 Days Ago                47
13 Days Ago               47
Name: count, dtype: int64

In [121]:
def convert_to_days(value):
    value = str(value).strip().lower()

    if value in ["just now", "few hours ago", "today"]:
        return 0
    
    if "30+ days" in value:
        return 31
    
    if "starts in" in value:
        return pd.NA
    
    if value == "unknown":
        return pd.NA
    
    match = re.search(r"(\d+)", value)
    
    if match:
        return int(match.group(1))
    
    return pd.NA


df["Days_Ago"] = df["Post_Time"].apply(convert_to_days).astype("Int64")

In [122]:
df[["Post_Time", "Days_Ago"]].drop_duplicates().sort_values(
    "Days_Ago",
    na_position="last"
).head(40)

0                  Post_Time  Days_Ago
310                 Just Now         0
169                    Today         0
186            Few Hours Ago         0
0                  1 Day Ago         1
604    Starts within 1 month         1
5                 2 Days Ago         2
176               3 Days Ago         3
2                 4 Days Ago         4
14                5 Days Ago         5
233               6 Days Ago         6
1                 7 Days Ago         7
16                8 Days Ago         8
18                9 Days Ago         9
3                10 Days Ago        10
9                11 Days Ago        11
242              12 Days Ago        12
24               13 Days Ago        13
28               14 Days Ago        14
1637   Starts : 15th Sep' 23        15
21               15 Days Ago        15
134              16 Days Ago        16
10               17 Days Ago        17
23               18 Days Ago        18
691              19 Days Ago        19
577              20 Days Ago        20
116              21 Days Ago        21
41               22 Days Ago        22
15               23 Days Ago        23
67               24 Days Ago        24
79               25 Days Ago        25
533              26 Days Ago        26
263              27 Days Ago        27
130              28 Days Ago        28
83               29 Days Ago        29
65               30 Days Ago        30
20              30+ Days Ago        31
17      Starts in 1-3 months      <NA>
36143                Unknown      <NA>

In [123]:
future_keywords = ["starts", "start"]

df.loc[
    df["Post_Time"].str.lower().str.contains("|".join(future_keywords), na=False),
    "Days_Ago"
] = pd.NA

In [124]:
df[df["Post_Time"].str.lower().str.contains("starts", na=False)][
    ["Post_Time", "Days_Ago"]
].drop_duplicates()

0                 Post_Time  Days_Ago
17     Starts in 1-3 months      <NA>
604   Starts within 1 month      <NA>
1637  Starts : 15th Sep' 23      <NA>

In [125]:
df["Days_Ago"].value_counts().sort_index().head(40)

Days_Ago
0     1422
1     6502
2     1581
3       38
4     5033
5     1482
6       47
7     1582
8     1696
9      166
10    1619
11    1441
12       9
13      47
14     187
15     199
16     134
17    1587
18     141
19      12
20      47
21     124
22     145
23    1237
24     133
25      13
26       5
27      66
28    1607
29     135
30     140
31    6195
Name: count, dtype: Int64

In [126]:
df["Days_Ago"].isna().sum()

np.int64(8681)

In [127]:
df["Post_Time"].value_counts().head(20)

Post_Time
Unknown                 7310
1 Day Ago               6502
30+ Days Ago            6195
4 Days Ago              5033
8 Days Ago              1696
10 Days Ago             1619
28 Days Ago             1607
17 Days Ago             1587
7 Days Ago              1582
2 Days Ago              1581
5 Days Ago              1482
11 Days Ago             1441
Starts in 1-3 months    1364
23 Days Ago             1237
Few Hours Ago            946
Just Now                 407
15 Days Ago              199
14 Days Ago              187
9 Days Ago               166
22 Days Ago              145
Name: count, dtype: int64

In [128]:
import re
import pandas as pd

def convert_to_days(value):
    value = str(value).strip().lower()

    # Current postings
    if value in ["just now", "few hours ago", "today"]:
        return 0

    # More than 30 days
    if "30+ days" in value:
        return 31

    # Future postings
    if "starts" in value:
        return pd.NA

    # Unknown
    if value == "unknown":
        return pd.NA

    # Normal "X Days Ago"
    match = re.search(r"(\d+)", value)

    if match:
        return int(match.group(1))

    return pd.NA


df["Days_Ago"] = (
    df["Post_Time"]
    .apply(convert_to_days)
    .astype("Int64")
)

In [129]:
df[["Post_Time", "Days_Ago"]].drop_duplicates().head(30)

0               Post_Time  Days_Ago
0               1 Day Ago         1
1              7 Days Ago         7
2              4 Days Ago         4
3             10 Days Ago        10
5              2 Days Ago         2
9             11 Days Ago        11
10            17 Days Ago        17
14             5 Days Ago         5
15            23 Days Ago        23
16             8 Days Ago         8
17   Starts in 1-3 months      <NA>
18             9 Days Ago         9
20           30+ Days Ago        31
21            15 Days Ago        15
23            18 Days Ago        18
24            13 Days Ago        13
28            14 Days Ago        14
41            22 Days Ago        22
65            30 Days Ago        30
67            24 Days Ago        24
79            25 Days Ago        25
83            29 Days Ago        29
116           21 Days Ago        21
130           28 Days Ago        28
134           16 Days Ago        16
169                 Today         0
176            3 Days Ago         3
186         Few Hours Ago         0
233            6 Days Ago         6
242           12 Days Ago        12

In [130]:
df["Days_Ago"].isna().sum()

np.int64(8681)

In [131]:
df.isnull().sum()

0
JOB_TITLES                 0
Company_Names              0
Experience_Required        0
Package_Details            0
Locations                  0
Skills                     0
Post_Url                   0
Post_Time                  0
Experience_Min         11038
Experience_Max         11038
Salary_Min             41014
Salary_Min_LPA         41014
Salary_Max_LPA         41014
Locations_Cleaned          0
Days_Ago                8681
dtype: int64

In [132]:
df.isnull().mean().mul(100).round(2)

0
JOB_TITLES              0.00
Company_Names           0.00
Experience_Required     0.00
Package_Details         0.00
Locations               0.00
Skills                  0.00
Post_Url                0.00
Post_Time               0.00
Experience_Min         25.40
Experience_Max         25.40
Salary_Min             94.39
Salary_Min_LPA         94.39
Salary_Max_LPA         94.39
Locations_Cleaned       0.00
Days_Ago               19.98
dtype: float64

In [133]:
df.shape

(43453, 15)

In [134]:
df.duplicated().sum()

np.int64(22318)

In [135]:
# 1. Completely empty rows
df.isna().all(axis=1).sum()

np.int64(0)

In [136]:
# 2. Completely empty columns
df.isna().all(axis=0).sum()

np.int64(0)

In [137]:
df.columns.tolist()

['JOB_TITLES',
 'Company_Names',
 'Experience_Required',
 'Package_Details',
 'Locations',
 'Skills',
 'Post_Url',
 'Post_Time',
 'Experience_Min',
 'Experience_Max',
 'Salary_Min',
 'Salary_Min_LPA',
 'Salary_Max_LPA',
 'Locations_Cleaned',
 'Days_Ago']

In [139]:
df = df.rename(columns={
    "JOB_TITLES": "Job_Title",
    "Company_Names": "Company_Name",
    "Experience_Required": "Experience_Required",
    "Package_Details": "Package_Details",
    "Locations": "Location",
    "Skills": "Skills",
    "Post_Url": "Job_URL",
    "Post_Time": "Post_Time",
    "Experience_Min": "Experience_Min",
    "Experience_Max": "Experience_Max",
    "Salary_Min": "Salary_Min",
    "Salary_Min_LPA": "Salary_Min_LPA",
    "Salary_Max_LPA": "Salary_Max_LPA",
    "Locations_Cleaned": "Location_Cleaned",
    "Days_Ago": "Days_Ago"
})

df.columns.tolist()

['Job_Title',
 'Company_Name',
 'Experience_Required',
 'Package_Details',
 'Location',
 'Skills',
 'Job_URL',
 'Post_Time',
 'Experience_Min',
 'Experience_Max',
 'Salary_Min',
 'Salary_Min_LPA',
 'Salary_Max_LPA',
 'Location_Cleaned',
 'Days_Ago']

Save

In [140]:
output_path = "C:/Users/jawah/OneDrive/Desktop/MCA MINI PROJECT - Copy/AI-Tech-Job-Market-Skills-Analytics/Data/cleaned/Dataset1_Cleaned.xlsx"

df.to_excel(output_path, index=False)

print("Dataset 1 cleaned and saved successfully!")
print("Shape:", df.shape)

Dataset 1 cleaned and saved successfully!
Shape: (43453, 15)